### ISSUE TITLE
Regarding Edit and continue

### ISSUE THREAD

**Issue by PrabhakarMano** [i-saint/Alcantarea#1]
To i-saint: This is regarding Edit and continue features, i am having some of the following queries
1)We are trying and debug the application using alcantarea it will be take the modifcation in second iteration. May i know the reason behind this.
2) If we did any changes in Main method in while looping that too also not reflecting?
Pls suggest your response on this. Thanks

**Comment by i-saint** [comment]
Alcantarea apply changes by replacing functions. (overwrite head of existing function with jmp to new one) so, as you guessing, changes for executing function can't be applied. in such case, you need to split functions.

**Comment by PrabhakarMano** [comment]
Thanks for response. we are understanding Alcantarea doing function patching.
**Can you guide us how to set the program counter in the same line of the modified function**

**Comment by i-saint** [comment]
I tried it once but gave up in the end. I think there is no API to feed debug information to debugger at runtime. probably you need to write your own debugger.
for such complicated case, more practical way is split your program into dlls (like UnrealEngine).
