### ISSUE TITLE
Simplify Alcantarea by loading .dll's in RAM

### ISSUE THREAD

**Issue by tapika** [i-saint/Alcantarea#2]
It would simplify hot reload support if .dll could be just reloaded as such, and compile and linking would be handled by visual studio IDE / build chain.

To support .dll re-loading - maybe it makes sense to load entire .dll into RAM so file lock would not be present and IDE can compile .dll out of box.

Loading .dll into RAM is something that is supported with some limitations by C#, but not native C++ - until now -

https://github.com/tapika/dllloader

This project demoes how dll can be loaded into RAM for windows. (Somehow similar approaches can be found for other os's - for example https://x-c3ll.github.io/posts/fileless-memfd_create/)

Maybe logic of hot reload could be recoded as:

- Load .dll into ram.
- Wait for .dll to change on file system
- Check that there is no ongoing build processes (presence of msbuild, devenv.com, cl.exe, link.exe, cmake is detected) - and reload .dll.. This most probably will work with native C++, with C++/cli support is also possible to achieve, but need to re-consider assembly strong naming.

**Comment by i-saint** [comment]
I won't update this project unless I really needed. but I think what you want is already done in my another project: https://github.com/i-saint/PatchLibrary
to reload dlls, I simply copied dll & pdb and modified path to pdb in the dll ( https://github.com/i-saint/PatchLibrary/blob/master/PatchLibrary/PatchLibrary.cpp#L85 ).
your approach seems more drastic. impressive.

**Comment by tapika** [comment]
With my library debugging works out of box, at least with native c++. But I havent tested yet how reloading would work with debugging. How about patch library?

**Comment by i-saint** [comment]
works with no problem.

**Comment by tapika** [comment]
Suspect that your approach will work only with native C++. dll compiled with C++/clr will probably won't work (as PE file format is extended to support .net / CLR stuff), but I haven't tried how well that one works with my solution.
